---
- name: Deploy Website
  hosts: DC.lab.itnsa.id
  tasks:
    - name: 1. Create DNS A record in lab.itnsa.id zone
      win_shell: |
        $nodeName = ("{{ site_name}}" -split '\.')[0]
        Add-DnsServerResourceRecordA -Name $nodeName -ZoneName "lab.itnsa.id" -IPv4Address "10.1.1.10" -ErrorAction SilentlyContinue

    - name: 2. Create root directory for website
      win_file:
        path: C:\project_website\{{ site_name }}
        state: directory

    - name: 3. Configure default index content for website
      win_copy:
        content: "{{ site_name }}"
        dest: C:\project_website\{{ site_name}}\index.html

    - name: 4. Create new IIS website
      win_iis_website:
        name: "{{ site_name }}"
        state: started
        port: 80
        hostname: "{{ site_name }}"
        physical_path: C:\project_website\{{ site_name }}
